const itemsData = [
  {
    id: 1,
    link: '/item/new/item1.html',
    category: 'product',
    name: '러블리 하트케이크',
    score: '4.5',
    review: 24,
    price: 40000,
    createdAt: new Date('2022-10-06'),
    image: '/images/cake/product/product1.jpg',
    tags: ["하트", "기념일"],
  },
  {
    id: 2,
    link: '#',
    category: 'product',
    name: '빈티지 메리 체리 케이크',
    score: '4.5',
    review: 46,
    price: 36000,
    createdAt: new Date('2022-10-07'),
    image: '/images/cake/product/product2.png',
    tags: ["빈티지", "생일"],
  },
  {
    id: 3,
    link: '#',
    category: 'product',
    name: '팔레트 케이크',
    score: '4.5',
    review: 42,
    price: 38000,
    createdAt: new Date('2022-10-07'),
    image: '/images/cake/product/product3.jpg',
    tags: ["디자인", "생일"],
  },
  {
    id: 4,
    link: '#',
    category: 'product',
    name: '달력 케이크',
    score: '4.5',
    review: 45,
    price: 35000,
    createdAt: new Date('2022-10-08'),
    image: '/images/cake/product/product4.png',
    tags: ["기념일", "디자인"],
  },
  {
    id: 5,
    link: '#',
    category: 'product',
    name: '감사패 케이크',
    score: '4.5',
    review: 56,
    price: 42000,
    createdAt: new Date('2022-10-08'),
    image: '/images/cake/product//product5.png',
    tags: ["어른", "선물"],
  },
  {
    id: 6,
    link: '#',
    category: 'product',
    name: '계란 한판 케이크',
    score: '4.5',
    review: 45,
    price: 48000,
    createdAt: new Date('2022-10-08'),
    image: '/images/cake/product/product6.jpg',
    tags: ["생일", "디자인"],
  },
  {
    id: 7,
    link: '#',
    category: 'product',
    name: '명품 가방 케이크',
    score: '4.5',
    review: 46,
    price: 43000,
    createdAt: new Date('2022-10-09'),
    image: '/images/cake/product/product7.jpg',
    tags: ["선물", "디자인"],
  },
  {
    id: 8,
    link: '#',
    category: 'product',
    name: '포토 케이크',
    score: '4.5',
    review: 72,
    price: 39000,
    createdAt: new Date('2022-10-09'),
    image: '/images/cake/product/product8.jpg',
    tags: ["사진", "기념일"],
  },
  {
    id: 9,
    link: '/item/design/item1.html',
    category: 'design',
    name: '티아라 케이크',
    score: '4.5',
    review: 14,
    price: 35000,
    createdAt: new Date('2022-10-02'),
    image: '/images/cake/design/design1.png',
    tags: ['파티', '브라이덜 샤워'],
  },
  {
    id: 10,
    link: '#',
    category: 'design',
    name: '로투스 케이크',
    score: '4.5',
    review: 42,
    price: 30000,
    createdAt: new Date('2022-10-03'),
    image: '/images/cake/design/design2.jpg',
    tags: ['과자', '신상'],
  },
  {
    id: 11,
    link: '#',
    category: 'design',
    name: '오레오 쇼콜라 갸또 케이크',
    score: '4.5',
    review: 54,
    price: 30000,
    createdAt: new Date('2022-10-03'),
    image: '/images/cake/design/design3.jpg',
    tags: ['초콜릿', '신상'],
  },
  {
    id: 12,
    link: '#',
    category: 'design',
    name: '체리쥬빌레 케이크',
    score: '4.5',
    review: 75,
    price: 30000,
    createdAt: new Date('2022-10-04'),
    image: '/images/cake/design/design4.jpg',
    tags: ['베스트셀러', '파티'],
  },
  {
    id: 13,
    link: '#',
    category: 'design',
    name: '헤이즐넛 로쉐 케이크',
    score: '4.5',
    review: 82,
    price: 32000,
    createdAt: new Date('2022-10-05'),
    image: '/images/cake/design/design5.jpg',
    tags: ['초콜릿', '친구'],
  },
  {
    id: 14,
    link: '#',
    category: 'design',
    name: '브라운 베어 케이크',
    score: '4.5',
    review: 83,
    price: 30000,
    createdAt: new Date('2022-10-06'),
    image: '/images/cake/design/design6.png',
    tags: ['베스트셀러', '캐릭터'],
  },
  {
    id: 15,
    link: '#',
    category: 'design',
    name: '스마일 케이크',
    score: '4.5',
    review: 91,
    price: 26000,
    createdAt: new Date('2022-10-07'),
    image: '/images/cake/design/design7.png',
    tags: ['친구', '캐릭터'],
  },
  {
    id: 16,
    link: '#',
    category: 'design',
    name: '데이지 케이크',
    score: '4.5',
    review: 35,
    price: 26000,
    createdAt: new Date('2022-10-07'),
    image: '/images/cake/design/design8.jpg',
    tags: ['캐릭터', '베스트셀러'],
  },
  {
    id: 17,
    link: '/item/ETC/item1.html',
    category: 'ETC',
    name: '미니 하트 초',
    score: '4.5',
    review: 53,
    price: 5000,
    createdAt: new Date('2022-10-02'),
    image: '/images/cake/etc/etc1.jpg',
    tags: ['초', '하트'],
  },
  {
    id: 18,
    link: '#',
    category: 'ETC',
    name: '곰돌이 초',
    score: '4.5',
    review: 47,
    price: 3000,
    createdAt: new Date('2022-10-03'),
    image: '/images/cake/etc/etc2.jpg',
    tags: ['초', '동물'],
  },
  {
    id: 19,
    link: '#',
    category: 'ETC',
    name: '스마일 미니 초',
    score: '4.5',
    review: 91,
    price: 3000,
    createdAt: new Date('2022-10-03'),
    image: '/images/cake/etc/etc3.jpg',
    tags: ['초', '이모티콘'],
  },
  {
    id: 20,
    link: '#',
    category: 'ETC',
    name: '해피벌스데이 토퍼',
    score: '4.5',
    review: 29,
    price: 3800,
    createdAt: new Date('2022-10-04'),
    image: '/images/cake/etc/etc4.jpg',
    tags: ['초', '글씨'],
  },
  {
    id: 21,
    link: '#',
    category: 'ETC',
    name: '레인보우 해피버스데이 토퍼',
    score: '4.5',
    review: 57,
    price: 3500,
    createdAt: new Date('2022-10-04'),
    image: '/images/cake/etc/etc5.jpg',
    tags: ['초', '글씨'],
  },
  {
    id: 22,
    link: '#',
    category: 'ETC',
    name: 'HBD 컬러 초',
    score: '4.5',
    review: 85,
    price: 3500,
    createdAt: new Date('2022-10-05'),
    image: '/images/cake/etc/etc6.jpg',
    tags: ['초', '글씨'],
  },
  {
    id: 23,
    link: '#',
    category: 'ETC',
    name: '파스텔 꽈배기 초',
    score: '4.5',
    review: 36,
    price: 5000,
    createdAt: new Date('2022-10-06'),
    image: '/images/cake/etc/etc7.jpg',
    tags: ['초'],
  },
  {
    id: 24,
    link: '#',
    category: 'ETC',
    name: '스프레이 토퍼',
    score: '4.5',
    review: 25,
    price: 5500,
    createdAt: new Date('2022-10-07'),
    image: '/images/cake/etc/etc8.png',
    tags: ['초'],
  },
];

export default itemsData;
